import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '../redux/provider';
import './globals.css';
import { useGetAllFormConfigQuery } from '@store/api/form-config-api';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const { isLoading, data } = useGetAllFormConfigQuery(null);

    if (isLoading) return <div>Loading...</div>;

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
